# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 80

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.100.11.147:3306/sms_manager?useUnicode=true&characterEncoding=UTF-8
        username: test
        password: WCpnhpTrQ6EppHW+
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

